#การรับค่าข้อมูลทางแป้นพิมพ์ด้วย python
name = input('ป้อนชื่อของคุณ: ')
yearBotn = input('ป้อนปีเกิดของคูณ: ')
old = (2023 - int(yearBotn))
print('...........................')
#ฟังก์ชันในการแปลงข้อความเป็นตัวเลข int(), float()
#ฟังก์ชันในการแปลงตัวเลขเป็นข้อความ str ()
print(f'ยินดีต้องรับ คุณ {name} เกิดปี {yearBotn} อายุ {old}')
print("ยินดีต้องรับ",name,"เกิดปี",yearBotn,"อายุ",old)
print("ยินดีต้องรับ"+ name +"เกิดปี"+ yearBotn +"อายุ"+ str(old))
print("ยินดีต้องรับ{}เกิดปี{}อายุ{}" .format(name,yearBotn,old))
print("ยินดีต้องรับ %s เกิดปี %s อายุ %d "%(name,yearBotn,old))
